# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class AdditionStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.add = channel.unary_unary(
        '/calculator.Addition/add',
        request_serializer=calculator__pb2.CalcRequest.SerializeToString,
        response_deserializer=calculator__pb2.CalcReply.FromString,
        )


class AdditionServicer(object):
  """The greeting service definition.
  """

  def add(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AdditionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'add': grpc.unary_unary_rpc_method_handler(
          servicer.add,
          request_deserializer=calculator__pb2.CalcRequest.FromString,
          response_serializer=calculator__pb2.CalcReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'calculator.Addition', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
