# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='calculator',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\x12\ncalculator\"#\n\x0b\x43\x61lcRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x16\n\tCalcReply\x12\t\n\x01\x63\x18\x01 \x01(\t2C\n\x08\x41\x64\x64ition\x12\x37\n\x03\x61\x64\x64\x12\x17.calculator.CalcRequest\x1a\x15.calculator.CalcReply\"\x00\x42\x36\n\x1bio.grpc.examples.calculatorB\x0f\x63\x61lculatorProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_CALCREQUEST = _descriptor.Descriptor(
  name='CalcRequest',
  full_name='calculator.CalcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='calculator.CalcRequest.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='calculator.CalcRequest.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=67,
)


_CALCREPLY = _descriptor.Descriptor(
  name='CalcReply',
  full_name='calculator.CalcReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='c', full_name='calculator.CalcReply.c', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['CalcRequest'] = _CALCREQUEST
DESCRIPTOR.message_types_by_name['CalcReply'] = _CALCREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalcRequest = _reflection.GeneratedProtocolMessageType('CalcRequest', (_message.Message,), dict(
  DESCRIPTOR = _CALCREQUEST,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.CalcRequest)
  ))
_sym_db.RegisterMessage(CalcRequest)

CalcReply = _reflection.GeneratedProtocolMessageType('CalcReply', (_message.Message,), dict(
  DESCRIPTOR = _CALCREPLY,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.CalcReply)
  ))
_sym_db.RegisterMessage(CalcReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.grpc.examples.calculatorB\017calculatorProtoP\001\242\002\003HLW'))

_ADDITION = _descriptor.ServiceDescriptor(
  name='Addition',
  full_name='calculator.Addition',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=93,
  serialized_end=160,
  methods=[
  _descriptor.MethodDescriptor(
    name='add',
    full_name='calculator.Addition.add',
    index=0,
    containing_service=None,
    input_type=_CALCREQUEST,
    output_type=_CALCREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADDITION)

DESCRIPTOR.services_by_name['Addition'] = _ADDITION

# @@protoc_insertion_point(module_scope)
